### ISSUE TITLE
Download link for the Windows build of 1.0 doesn't work

### ISSUE THREAD

**Issue by a-ramsay** [drunner/drunner#106]
The link in the documentation returns a 403:
`https://s3-ap-southeast-2.amazonaws.com/drunner/10/win/drunner.exe`

I have also tried using the domain from the Linux build which also returns a 403:
`wget https://drunner.s3.amazonaws.com/10/win/drunner.exe`

The actual Linux download link works though.

**Comment by j842** [comment]
Builds were failing on AppVeyor. Fixed in 9cbe635d9dca5d414b60d9be70b2d5fb912f76b4
