### ISSUE TITLE
Restore the drunner/root_utils container

### ISSUE THREAD

**Issue by a-ramsay** [drunner/drunner#107]
Currently new installs of dRunner 0.6 will fail because the `drunner/root_utils` container is no longer available on DockerHub. We still rely on 0.6 in production so would greatly appreciate this container being republished :)

**Comment by j842** [comment]
Need to either update 0.6 to use the latest image or reinstate the old root_utils (probably latter).

**Comment by j842** [comment]
Reinstated rootutils (note it's rootutils, not root_utils!)
