### ISSUE TITLE
Moving to CMake

### ISSUE THREAD

**Issue by p-jackson** [drunner/drunner#15]
Created a discussion issue to talk about moving the build to CMake.

First point: CMake usually does "out of source builds". This means that while the `CMakeList.txt` files that describe the project are committed to git, the IDE files and Makefile files it generates are generated in *another* directory so they don't pollute the repo folder.
This isn't mandatory; you can also do "in source builds" and just .gitignore the generated files.

What would you do?

**Comment by j842** [comment]
"Out of source builds" sounds good to me. I like generated files being in a separate directory where it's not too inconvenient.

**Comment by j842** [comment]
Had a prototype going with CMake. Worked, but didn't feel compelling, so went back to make (Linux/OSX) and VS solution.
