### ISSUE TITLE
Add flag to allow containers to run as root

### ISSUE THREAD

**Issue by infmon** [drunner/drunner#31]
Currently, drunner won't allow containers to run if they run as the root user.  This behaviour should stay as the default, but allowing a dservice to specify a flag that switches the behaviour off would be very useful, specifically when pulling in other external containers for things like Redis.

Installing a dservice that can run containers as root should show a big warning so that users know what they're getting into

**Comment by j842** [comment]
Addcontainer now has a runasroot flag.

https://github.com/drunner/drunner/blob/master/DSERVICE.md#configuration
