### ISSUE TITLE
Link error building from source on OS X

### ISSUE THREAD

**Issue by JohnRGee** [drunner/drunner#36]
A number of the LDFLAGS flags in the makefile on master branch are not supported by clang on OS X, one error and two warnings. Simply removing the flag(s) allows a link.

Initially the link fails with:
`clang: error: unsupported option '-static-libgcc'`

Removing that then generates two warnings:
```clang: warning: argument unused during compilation: '-static-libstdc++'
clang: warning: argument unused during compilation: '-pthread'```

Of interest for the static flags is that Apple strongly discourages statically linked binaries. Statically linking libraries are fine though.
[Statically linked binaries on Mac OS X](https://developer.apple.com/library/mac/qa/qa1118/_index.html)

**Comment by j842** [comment]
@JohnRGee  -can you try with the updated master branch please? (changeset bc7d1c9 )

I don't have a Mac I can try this on myself.

**Comment by JohnRGee** [comment]
Short version: yes, thanks

(And I'll make a change in similar vein for consideration to add Brew locations to search paths for Poco.)
