### ISSUE TITLE
CRITICAL : dRunner needs to respect tags on update

### ISSUE THREAD

**Issue by infmon** [drunner/drunner#44]
Currently, when updating a dService, dRunner pulls the latest image.  But if a dService was installed with a specific tag (such as a feature branch), that tag needs to be respected.  We will also need to be able to change the tag to update to in the future.  Two use cases:

dRunner install mydservice:feature_branch

This installs the mydservice image tagged as 'feature_branch'.  If a new version of that feature branch is built, the new image will be given the export_published tag, so "drunner update mydservice" needs to pull the correctly tagged image.  Currently, it pulls the image tagged as 'latest'.

dRunner install mydservice:2.4.1

This installs the mydservice image tagged as '2.4.1'.  This image won't ever be changed, as it's a released version, but we need a way to tell drunner to change to using the '2.4.2' tagged image when updating to the next version.

We particularly need this for our current usage, rather than future use.  I'm going to try to take a fork of dRunner before version 4 development happened...

**Comment by infmon** [comment]
It's actually worse than that.  If I specify the tag to use in drunner install, that image is pulled down and used as a starting point, but the actual images used to run the dService are specified within the docker-compose file, and at the point where drunner is installing I can't think of a good way to specify the tag (can't be built into the source files, as that would risk the feature tag getting through into production).  I guess I could make a separate docker-compose file that has the tag specified through a variable that I use to actually run the containers, but that seems rather round-about

**Comment by infmon** [comment]
So, if I :
- Add a docker-compose-real.yml, which has image: "mydservice:${IMAGE_TAG}" rather than just image: "mydservice"
- Make that the file passed to docker-compose within my servicerunner
- add a configuration that uses save_environment to set the IMAGE_TAG

Then the install case works.  The correct image is used as a starting point, drunner reads the (wrong) docker-compose file to download images, then the servicerunner runs the correct docker-compose file to actually run containers.

Updating won't work though, as drunner update just updates the images specified in the (wrong) docker-compose.yml file

**Comment by j842** [comment]
Fixed in dRunner 0.8 stable.
