### ISSUE TITLE
More configuration options/workflows

### ISSUE THREAD

**Issue by infmon** [drunner/drunner#52]
At the moment, drunner allows you to specify config values, which can then be set through the configure action.  But I'd really like to be able to do more through the configure action.  For example, in the old version of dconsul we have:

```
         configure)
            if [ -z "$AWS_REGION" ]; then die "Configure requires AWS_REGION environment variable."; fi
            if [ -z "$DNS_ADDRESS" ]; then die "Configure requires DNS_ADDRESS environment variable."; fi
            if [ -z "$IS_SERVER" ]; then die "Configure requires IS_SERVER environment variable."; fi
            # VAULT_TOKEN is optional
            
            # Store instance id
            save_environment "INSTANCE_ID" $(curl -s http://169.254.169.254/latest/meta-data/instance-id)

            if [ $IS_SERVER -eq 1 ]; then
               save_environment "AGENT_TYPE" "ConsulServer"
            else
               save_environment "AGENT_TYPE" "ConsulAgent"
            fi

            docker-compose -p "${SERVICENAME}" run --rm dconsul configure.py $AWS_REGION $DNS_ADDRESS $IS_SERVER $VAULT_TOKEN
            ;;
```

So we're:

1. Getting in some parameters but not storing them as environment variables
2. Storing some environment variables that aren't parameters
3. Running a configuration script that makes use of the parameters to (in this case) build up the actual configuration files we need within the containers volumes.

Maybe we can already do some/all of that in the new drunner, but I'm not sure how.

**Comment by j842** [comment]
I'd suggest dynamically assigning derived values such as AGENT_TYPE and passing via docker-compose -e flag ( https://docs.docker.com/compose/environment-variables/ ) to set.

Instance ID could be handled similarly, or if you didn't want to run curl every time the service started you could store it using the new dconfig_set helper function:
https://github.com/drunner/drunner/blob/master/DSERVICE.md#helper-functions
