### ISSUE TITLE
Run whole string commands through drun?

### ISSUE THREAD

**Issue by infmon** [drunner/drunner#56]
Is it possible to run whole string commands in drun, without breaking them up into component arguments?

For example, in dproject we use drun_output to call setup_git.  The result of setup_git is:

git config --global user.name "My name"
git config --global user.email myemail@mydomain.com

I want to then run that as two more commands.  I can split each line into a separate string, but splitting them into separate args is hard (e.g. splitting the first line into ["git", "config", "--global", "user.name", "My name"]

**Comment by infmon** [comment]
I think I solved the splitting problem with the following:

```
function splitString(input)
   local result = {}
   local index = 1
   local spat, epat, buf, quoted = [=[^(['"])]=], [=[(['"])$]=]
   for str in input:gmatch("%S+") do
      local squoted = str:match(spat)
      local equoted = str:match(epat)
      local escaped = str:match([=[(\*)['"]$]=])
      if squoted and not quoted and not equoted then
         buf, quoted = str, squoted
      elseif buf and equoted == quoted and #escaped % 2 == 0 then
         str, buf, quoted = buf .. ' ' .. str, nil, nil
      elseif buf then
         buf = buf .. ' ' .. str
      end
      if not buf then
         result[index] = (str:gsub(spat,""):gsub(epat,""))
         index = index + 1
      end
   end
   ---if buf then print("Missing matching quote for "..buf) end
   return result
end
```

However, the resulting table, when passed to drun, causes a segmentation fault...

**Comment by infmon** [comment]
I figured out the way to get around this.  Using the above function you can split the command line string into arguments.  Then pass those into drunner via table.unpack (so drun(table.unpack(splitString(comamndline)))

**Comment by j842** [comment]
That's a lot of work, I'll see if I can make it easier. :-)

**Comment by j842** [comment]
drun now supports tables as the argument.
Also added dsplit. Examples:

function testsplit(...)

   print("manual table")
   result = drun({"ls","-l","/"})

   print("dsplit")
   result = drun(dsplit('ls -f /'))

   return result
end
