### ISSUE TITLE
Add ability to change directory

### ISSUE THREAD

**Issue by a-ramsay** [drunner/drunner#65]
Some of our dServices rely on knowing the current working directory and being able to switch to it for mapping host files to a container for live development, creating files on disk, etc.

Previously we could capture the working directory in a bash variable `WORKDIR="$(pwd)"` and then `cd $WORKDIR` for local file operations and `cd $MYDIR` for accessing compose files, etc.

It would be great to be able to have this functionality in the new service.lua format.

**Comment by j842** [comment]
Added getpwd() and setpwd(dir).  They store a directory which is used for drun commands. Lua doesn't seem to have a concept of pwd by default, but you can add getpwd() to other strings at least.

Let me know if extra things would help.

See pull request drunner/pull/70 

https://github.com/drunner/drunner/blob/65771979005419e75d44aaeed8977da067e0fc6b/DSERVICE.md

**Comment by j842** [comment]
Updated to be:

getdrundir()	Returns the current drun directory.
setdrundir( dir )	Sets the drun directory. If no argument passed resets to default (the dService folder on the host).
getpwd()	Returns the current directory.
