### ISSUE TITLE
dconfig_get() doesn't work inside drunner_setup()

### ISSUE THREAD

**Issue by FraserThompson** [drunner/drunner#94]
I'm trying to get a config variable inside drunner_setup(), like this:

```
addconfig("ENV", "Environment.", "latest", "string", true, true)
addcontainer('nginx-drupal:'..dconfig_get('ENV'))
```

But I get this error on build:

`|ERROR|2017-01-23 06:45| Service Variables pointer has not been set.`

**Comment by j842** [comment]
No longer relevant in dRunner 1.0.
